steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/qbo-webhook-mapper', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/qbo-webhook-mapper']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'qbo-webhook-mapper'
      - '--image=gcr.io/$PROJECT_ID/qbo-webhook-mapper'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--update-env-vars=NODE_ENV=production,USE_MOCK_DATA=false,QBO_ENVIRONMENT=sandbox,QBO_REDIRECT_URI=https://qbo-webhook-mapper-666004421830.us-central1.run.app/api/oauth/qbo/callback,BACKEND_URL=https://qbo-webhook-mapper-666004421830.us-central1.run.app'
      - '--update-secrets=QBO_CLIENT_ID=qbo-client-id:latest,QBO_CLIENT_SECRET=qbo-client-secret:latest'

images:
  - 'gcr.io/$PROJECT_ID/qbo-webhook-mapper'

timeout: '1200s'
